# Generated by Django 4.1.7 on 2023-03-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(max_length=1)),
                ('sucursal', models.CharField(max_length=20)),
                ('especialidad', models.CharField(max_length=20)),
                ('clinica', models.CharField(max_length=20)),
                ('sanatorio', models.CharField(max_length=20)),
            ],
        ),
    ]
